apiVersion: v1
kind: Secret
metadata:
  name: external-dns-azure
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  azure.json: |
    {
      "tenantId": "ef7a487a-77ca-410a-803d-e426b62a587f",
      "subscriptionId": "49819e64-4f1b-47f5-8c73-1cee002673c7",
      "resourceGroup": "rg-cloud-k8s-lab-dev-ause-01",
      "useWorkloadIdentityExtension": true
    }